A container and Top menu bar
fossasia/2014.fossasia.org pull request #24
Opened 2017-12-08 17:36 UTC by samyakbvs

Container increases the code quality and also #17 fixed

2017-12-08 17:38 UTC, samyakbvs commented
I won't be able to provide a deployment link but here's a screenshot of the what will the site look like
![screen shot 2017-12-08 at 11 03 56 pm](https://user-images.githubusercontent.com/34275800/33777888-88bb22da-dc6c-11e7-9241-cb12ab0b6a75.png)
Also, I assure you that links are working perfectly

2017-12-08 17:40 UTC, anshumanv commented on _site/index.html
> +	<ul class="sf-menu"><li class="leaf first no-dhtml "><a href="https://2014.fossasia.org/wrap-up" title="FOSSASIA 2014 Wrap up" id="dhtml_menu-3672">Wrap Up</a></li>
Correct indentation of this block please.

2017-12-08 17:45 UTC, samyakbvs commented
Is it ready to merge?

2017-12-09 05:55 UTC, anshumanv requested changes

2017-12-09 05:55 UTC, anshumanv commented on _site/index.html
> +<li class="leaf  no-dhtml "><a href="https://2014.fossasia.org/schedule" id="dhtml_menu-3501">Schedule</a></li>
Please indent all the child elements of the container accordingly.

2017-12-09 06:39 UTC, anshumanv commented
It should go like
```
container
    ul
        li
   /ul
/container
```

Please follow @samyakbvs

2017-12-09 06:43 UTC, samyakbvs commented
Okay

2017-12-09 06:45 UTC, anshumanv commented
Also please don't change other lines of code apart from the one you're adding.

2017-12-09 06:59 UTC, anshumanv commented
Thanks, the indentation loos fine now, can you please check on the colors? This doens't look close to the header nav we have at - https://fossasia.org/

2017-12-09 07:00 UTC, samyakbvs commented
Just the colours or something else too?

2017-12-09 08:01 UTC, samyakbvs commented
@anshumanv

2017-12-09 09:09 UTC, anshumanv commented
Thanks for the changes, let me ask others too.

2017-12-09 09:11 UTC, anshumanv approved these changes

2017-12-09 10:03 UTC, the-codingninja requested changes
Resolve conflicts

2017-12-09 14:47 UTC, samyakbvs commented
now can it merge

2017-12-09 14:51 UTC, samyakbvs commented
@ms10398

2017-12-09 15:07 UTC, the-codingninja approved these changes

2017-12-09 15:17 UTC, samyakbvs commented
Now can it merge?

2017-12-09 15:18 UTC, samyakbvs commented
@ms10398 and @anshumanv

2017-12-09 15:21 UTC, merged

2017-12-09 16:13 UTC, samyakbvs commented
Please approve my task now @anshumanv and @ms10398

2017-12-09 16:28 UTC, mariobehling commented
Not seeing improvements on the site.

2017-12-09 16:31 UTC, mariobehling commented on _site/index.html
> +	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossor
What do we need this for? Avoid additional dependencies.