Fixes #28: Make site in design of Fossasia main site
fossasia/2014.fossasia.org pull request #57
Opened 2017-12-27 12:10 UTC by Ploypiti

Fixes #28 
[Preview here](https://ploypiti.github.io/2014.fossasia.org/)

- Change fonts & Color to match the main site
- Change menu and hover color
- Remove shadow from sponsor logo and expand the logo on hover instead
- Fix the header & text that wasn't working
- Change readme.md from `Google code-in site` to `Fossasia summit 2014`

2017-12-27 12:21 UTC, nzec reviewed
Woah! Did a lot of work! Please rebase, all the newest changes in the main repository are not present in yours.

2017-12-27 13:15 UTC, gabru-md approved these changes
LGTM

2017-12-27 13:37 UTC, akshatnitd requested changes
Please check indentation issues. Rest all looks good for this PR. Also, you can open up issues after it gets merged for other design issues, like changing background color of drop-down in header buttons, etc.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +			padding: 0px;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +      border-radius: 15px;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +  font-weight: 400;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +  font-size: 12px;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +  border-bottom-style: solid;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +  border: none;
Please correct the indentation.

2017-12-27 13:37 UTC, akshatnitd commented on _includes/header.html
> +  padding: 15px;
Please correct the indentation.

2017-12-27 13:55 UTC, akshatnitd commented
Also, you can remove these errors by moving to `https`
![screenshot from 2017-12-27 19-25-04](https://user-images.githubusercontent.com/12656846/34383515-ad21f350-eb3b-11e7-9745-c34aec398f67.png)

2017-12-27 20:13 UTC, ParthS007 requested changes
@Ploypiti Please do the suggested change

2017-12-28 01:56 UTC, Ploypiti commented
@akshatnitd @ParthS007 Done.

2017-12-28 01:59 UTC, Ploypiti commented
Btw should we remove the `_site` file since there's no use of it..? I mean everything are in .md file *outside* and CSS changes made in `_site` doesn't work.

2017-12-28 07:30 UTC, ParthS007 approved these changes
Looks cool 👍

2017-12-28 07:36 UTC, Ploypiti commented
@ParthS007 Please merge.

2017-12-28 08:17 UTC, akshatnitd requested changes
There still are indentation issues. Please fix those!

2017-12-28 08:55 UTC, Ploypiti commented
@akshatnitd Fixed (Hope this is the last time..?).

2017-12-28 09:10 UTC, akshatnitd requested changes
Check the indentation issues, where I had pointed out in my first review. All the changes are pending. I guess you are having problems due to tabs and spaces.Check that once.

2017-12-28 09:10 UTC, akshatnitd commented on _includes/header.html
> +  letter-spacing: 1px;
See indentation here

2017-12-28 13:39 UTC, akshatnitd approved these changes
Looks good now :) 
Happy to see the patience growing with time :100: 

Now, you can open up issues for other design issues, like changing background color of drop-down in header buttons, etc.

2017-12-28 13:39 UTC, merged

2017-12-28 14:08 UTC, kubami9 commented
Excuse me, I know it's not really a good place to ask but fossasia gitter chat is down and I'm really stuck. I have a problem with `jekyll serve` command, after running, automatically more than 50 files are changed/added/deleted even though I don't touch anything. 
Is there any place, chatroom etc. where I can find help? Sorry for bothering 😅

2017-12-28 14:16 UTC, duttaditya18 commented
@kubami9 Use the new FOSSASIA gitter chat. (It is a private channel.)

2017-12-28 14:21 UTC, kubami9 commented
@duttaditya18 Could you give me the link?

2017-12-28 14:23 UTC, duttaditya18 commented
I added you to the room. Please check.