Fixed #53: Added icons and fixed links
fossasia/2014.fossasia.org pull request #60
Opened 2017-12-27 19:55 UTC by samyakbvs

Added Icons instead of plain text and fixed the bugged link for github

2017-12-27 19:56 UTC, samyakbvs commented
https://samyakbvs.github.io/samyak--2014.fossasia.org/

2017-12-27 20:31 UTC, 0x48piraj commented on _includes/footer.html
> +			<a href="https://twitter.com/fossasia?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i align="left" style="padding: 3px; color: #000000; font-size: xx-large;" class="fa fa-twitter-square
It's a bad link, consisting of several `ref` redirects. fix them.

2017-12-27 20:31 UTC, 0x48piraj requested changes
See the code review. Cheers :+1:

2017-12-28 08:28 UTC, abishekvashok requested changes

2017-12-28 08:28 UTC, abishekvashok commented on _includes/footer.html
> +
You got some tabs here. Remove em pls.

2017-12-28 08:28 UTC, abishekvashok commented on _includes/footer.html
> +		<div class="container">
Please properly intend

2017-12-28 08:53 UTC, samyakbvs commented
Changes made @abishekvashok

2017-12-28 12:01 UTC, harshit98 approved these changes

2017-12-28 12:02 UTC, merged

2017-12-28 13:39 UTC, abishekvashok commented
Good job