Add Top section solves #56
fossasia/2014.fossasia.org pull request #79
Opened 2017-12-30 16:56 UTC by kubami9

### Add top section similar to most FOSSASIA websites. Fix #56 

**This PR includes:**
 - full width header with FOSSASIA background-image (the same which is on FOSSASIA Summit 2012 and 2018)
 - partners/sponsors section which includes all content which has been in the sidebar, apart from the Flickr images
 - delete sidebar
 - FOSSASIA newsletter section (basically email subscription from sidebar turned into own section, somewhat similar to this from fossasia.org)
 - center content
 - menu background changed to transparent and font color to white
 - some simple bug and typo fixes

Preview link: https://kubami9.github.io/2014.fossasia.org-km-contribute/

2017-12-30 17:14 UTC, isuruAb requested changes
Hello @kubami9  there are some changes to be done.
logo is missing and font size should be little bit smaller. please follow the styles of fossasia.org and don't forget to squash your commits.
cheers

2017-12-30 18:09 UTC, kubami9 commented
@isuruAb done 😄

2017-12-30 18:20 UTC, codedsun commented on _includes/header.html
> +      		text-transform: uppercase;
The indentation needs to be corrected

2017-12-31 11:32 UTC, kubami9 commented
@isuruAb could you check out my changes 😄 this PR is getting more and more conflicts to resolve and whenever I resolve them I need to squash and it all loops

2017-12-31 18:29 UTC, ParthS007 approved these changes

2018-01-01 08:22 UTC, akshatnitd reviewed
The changes looks good. You just need to fix the indentation issues at various lines, keeping in view the best practices. And, lastly squash the commits! The, it would be good to go :+1:

2018-01-01 09:48 UTC, kubami9 commented
@akshatnitd Is it good now?

2018-01-01 10:51 UTC, nzec approved these changes
There are a lot of problems but I think they can be improved over time with different issues. 

I think this should be merged first.

@kubami9 Awesome work! 👍

2018-01-01 10:53 UTC, akshatnitd requested changes

2018-01-01 10:53 UTC, akshatnitd commented on _includes/header.html
> +  background-image: url(images/fossasia2016.jpg);
Missing indentation here and same in many lines below. Also, I can see 2 commits, make sure only 1 commit remains after squashing.

2018-01-01 11:25 UTC, duttaditya18 commented on _includes/header.html
> +<<<<<<< HEAD
Fix merge errors.

2018-01-01 11:34 UTC, kubami9 commented
It's confusing, whenever I squash commits it gets conflicts and whenever I resolve conflicts it needs to be squashed

2018-01-01 11:35 UTC, kubami9 commented
And now - I don't even know why - it shows me that I changed 93 files

2018-01-01 11:39 UTC, kubami9 commented
@akshatnitd  Now it should be okay, however I can't merge it into just one commit since it's giving dozens of conflicts

2018-01-01 12:24 UTC, akshatnitd approved these changes
Good work! :) Merging :rocket: 
Further improvements can be done by next PRs.

2018-01-01 12:24 UTC, merged

2018-01-01 12:42 UTC, kubami9 commented
Yaay! Thank you so much @akshatnitd!!! 😃